#!/bin/bash

echo "🚀 OpenSearch React UI - Available Commands"
echo "==========================================="
echo ""
echo "📋 Quick Start Commands:"
echo "  ./build-and-run.sh              # Build and run in production mode"
echo "  ./build-and-run.sh --dev        # Build and run in development mode"
echo "  ./run-all.sh                    # Run everything (requires existing build)"
echo ""
echo "🏗️  Build Commands:"
echo "  ./build-all.sh                  # Complete build with testing and validation"
echo "  npm run build                   # Basic React build"
echo "  npm run build:all               # Same as ./build-all.sh"
echo ""
echo "🚀 Run Commands:"
echo "  ./run-all.sh                    # Start proxy server + React dev server"
echo "  ./run-all.sh --proxy-only       # Start only the proxy server"
echo "  ./run-all.sh --check-services   # Check what services are running"
echo "  npm run start                   # Start React dev server only"
echo "  npm run server                  # Start proxy server only"
echo ""
echo "🔧 Build + Run Commands:"
echo "  ./build-and-run.sh              # Build and run in production mode"
echo "  ./build-and-run.sh --dev        # Build and run in development mode"
echo "  ./build-and-run.sh --build-only # Build only, don't run"
echo "  ./build-and-run.sh --serve-port 8080  # Custom port for production"
echo ""
echo "🗄️  Data Management:"
echo "  npm run index-data              # Create and populate OpenSearch index"
echo ""
echo "🧹 Clean Commands:"
echo "  ./clean.sh                      # Complete project cleanup"
echo "  npm run clean:build             # Remove build folder"
echo "  npm run clean:deps              # Remove node_modules and lock file"
echo "  npm run clean:cache             # Clear npm cache"
echo "  npm run clean:all               # Remove build, deps, cache, logs"
echo ""
echo "🧪 Testing:"
echo "  npm test                        # Run tests in watch mode"
echo "  npm test -- --watchAll=false    # Run tests once"
echo ""
echo "📦 NPM Script Shortcuts:"
echo "  npm run build-and-run           # Same as ./build-and-run.sh"
echo "  npm run build-and-run:dev       # Same as ./build-and-run.sh --dev"
echo "  npm run build-and-run:prod      # Same as ./build-and-run.sh --prod"
echo "  npm run run:all                 # Same as ./run-all.sh"
echo "  npm run run:proxy-only          # Same as ./run-all.sh --proxy-only"
echo ""
echo "🔍 Service Information:"
echo "========================"
echo "• OpenSearch:     http://localhost:30920"
echo "• Proxy Server:   http://localhost:4000"
echo "• React App:      http://localhost:3000 (dev) or custom port (prod)"
echo ""
echo "📚 Prerequisites:"
echo "=================="
echo "• Node.js 16+ (current: $(node --version 2>/dev/null || echo 'not installed'))"
echo "• npm (current: $(npm --version 2>/dev/null || echo 'not installed'))"
echo "• OpenSearch running on localhost:30920"
echo "• curl for health checks"
echo ""
echo "🆘 Common Issues:"
echo "=================="
echo "• OpenSearch not running: Start OpenSearch on port 30920"
echo "• Port conflicts: Scripts will try alternative ports automatically"
echo "• Build fails: Run 'npm run clean:all' then 'npm install'"
echo "• Tests fail: Known issue with axios/Jest compatibility"
echo ""
echo "📖 For detailed help:"
echo "======================"
echo "  ./build-all.sh --help"
echo "  ./run-all.sh --help"
echo "  ./build-and-run.sh --help"
echo ""
echo "💡 Tip: Use './build-and-run.sh' for the fastest complete setup!"
echo ""
